getTab_sysP_variedades<-function(){
  tabPanel("Variedades",
    h2("Variedades"),
    dispNewPlotGeneric(plotName="Var",isRGB=TRUE,isDownload=TRUE),
    dispNewPlotGeneric(plotName="Var1",isRGB=TRUE,isDownload=TRUE),
    dispNewPlotGeneric(plotName="Var2",isRGB=TRUE,isDownload=TRUE),
    dispNewPlotGeneric(plotName="Var3",isRGB=TRUE,isDownload=TRUE)
  )
}